services:
  - type: web
    name: nav-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
